security:
    encoders:
        App\Entity\User:
            algorithm: auto
        App\Entity\Salarie:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Salarie
                property: email
    role_hierarchy:
        ROLE_ADMIN: [ROLE_RESPONSABLE_RH]
        ROLE_RESPONSABLE_RH: [ROLE_RESPONSABLE_SERVICE]
        ROLE_RESPONSABLE_SERVICE: [ROLE_SALARIE]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            user_checker: App\Security\UserChecker
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000
            switch_user: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/initialisation-compte, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_SALARIE }

